# Generated by Django 2.0.6 on 2018-09-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspberium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',), 'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(help_text='This is the address of a Kasa Smart Plug.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='pin',
            field=models.IntegerField(help_text='This is the physical pin that the device is connected to.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('off', 'Off'), ('on', 'On'), ('auto', 'Auto')], help_text='This is the default state of the device.', max_length=4),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='off', editable=False, max_length=3),
        ),
    ]
