# Generated by Django 2.0.6 on 2018-06-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pin', models.IntegerField()),
                ('state', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
